version: "3"
services:
  sqlex_db:
    image: "postgres:12"
    container_name: "sqlex_db"
    ports:
      - "5432:5432"
    volumes:
      - sqlex_dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
volumes:
  sqlex_dbdata: